# Generated by Django 2.2 on 2023-01-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0003_auto_20230129_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_id',
            new_name='line_id',
        ),
    ]
