# Generated by Django 2.2 on 2023-02-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0005_auto_20230218_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_condition',
            field=models.CharField(choices=[('新品', '新品'), ('美品', '美品'), ('上', '上'), ('中', '中'), ('下', '下')], default=None, max_length=10),
        ),
    ]
