# Generated by Django 2.2 on 2023-02-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0006_auto_20230223_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
